<?php
use CRM_Search_ExtensionUtil as E;

// Adds option group for SearchDisplay.type
return [
  [
    'name' => 'SearchDisplayType',
    'entity' => 'OptionGroup',
    'update' => 'always',
    'cleanup' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'search_display_type',
        'title' => 'Search Display Type',
        'description' => NULL,
        'data_type' => NULL,
        'is_reserved' => TRUE,
        'is_active' => TRUE,
        'is_locked' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'icon',
          'description',
          'visibility',
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SearchDisplayType:table',
    'entity' => 'OptionValue',
    'cleanup' => 'always',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'search_display_type',
        'value' => 'table',
        'name' => 'crm-search-display-table',
        'label' => E::ts('Table'),
        'icon' => 'fa-table',
        'grouping' => NULL,
        'filter' => 0,
        'is_default' => FALSE,
        'description' => E::ts('Displays results as rows and columns'),
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'color' => NULL,
        'component_id' => NULL,
        'domain_id' => NULL,
        'visibility_id:name' => 'public',
      ],
      'match' => ['option_group_id', 'name'],
    ],
  ],
  [
    'name' => 'SearchDisplayType:list',
    'entity' => 'OptionValue',
    'cleanup' => 'always',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'search_display_type',
        'value' => 'list',
        'name' => 'crm-search-display-list',
        'label' => E::ts('List'),
        'icon' => 'fa-list',
        'grouping' => NULL,
        'filter' => 0,
        'is_default' => FALSE,
        'description' => E::ts('Displays results as numbered or bulleted list'),
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'color' => NULL,
        'component_id' => NULL,
        'domain_id' => NULL,
        'visibility_id:name' => 'public',
      ],
      'match' => ['option_group_id', 'name'],
    ],
  ],
  [
    'name' => 'SearchDisplayType:grid',
    'entity' => 'OptionValue',
    'cleanup' => 'always',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'search_display_type',
        'value' => 'grid',
        'name' => 'crm-search-display-grid',
        'label' => E::ts('Grid'),
        'icon' => 'fa-th',
        'grouping' => NULL,
        'filter' => 0,
        'is_default' => FALSE,
        'description' => E::ts('Gallery-style grid works well for image thumbnails'),
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'color' => NULL,
        'component_id' => NULL,
        'domain_id' => NULL,
        'visibility_id:name' => 'public',
      ],
      'match' => ['option_group_id', 'name'],
    ],
  ],
  [
    'name' => 'SearchDisplayType:autocomplete',
    'entity' => 'OptionValue',
    'cleanup' => 'always',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'search_display_type',
        'value' => 'autocomplete',
        'name' => 'crm-search-display-autocomplete',
        'label' => E::ts('Autocomplete'),
        'icon' => 'fa-commenting-o',
        'grouping' => NULL,
        'filter' => 0,
        'is_default' => FALSE,
        'description' => E::ts('Customize an autocomplete form field'),
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'color' => NULL,
        'component_id' => NULL,
        'domain_id' => NULL,
        'visibility_id:name' => 'admin',
      ],
      'match' => ['option_group_id', 'name'],
    ],
  ],
];
