<?php

namespace Civi\Api4\Utils;

use Civi\Core\Event\GenericHookEvent;

/**
 * Trait AfformGetTrait
 *
 * Shared logic for the Get action of Afform and AfformTemplate.
 */
trait AfformGetTrait {

  use AfformFormatTrait;

  abstract protected function getScannerServiceName(): string;

  abstract protected function getHookName(): string;

  abstract protected function getHookParamKey(): string;

  abstract protected function addExtraComputedFields(array &$records);

  public function getRecords() {
    $records = [];

    $scanner = \Civi::service($this->getScannerServiceName());

    // Optimization: only fetch extra data if requested
    $getComputed = $this->_isFieldSelected('has_local', 'has_base', 'base_module');
    $getSearchDisplays = $this->_isFieldSelected('search_displays');
    $getLayout = $getSearchDisplays || $this->_isFieldSelected('layout');
    // To optimize lookups by file/module/directive name
    $getNames = array_filter([
      'name' => $this->_itemsToGet('name'),
      'module_name' => $this->_itemsToGet('module_name'),
      'directive_name' => $this->_itemsToGet('directive_name'),
    ]);
    // To optimize lookups by type
    $getTypes = $this->_itemsToGet('type');

    $names = $getNames['name'] ?? array_keys($scanner->findFilePaths());

    // Allow hooks to provide autoGenerated items
    $hookForms = [];
    $hookParams = [$this->getHookParamKey() => &$hookForms, 'getNames' => $getNames, 'getTypes' => $getTypes, 'getLayout' => $getLayout];
    $event = GenericHookEvent::create($hookParams);
    \Civi::dispatcher()->dispatch($this->getHookName(), $event);
    // Set defaults for items supplied by hook
    foreach ($hookForms as $item) {
      $names[] = $item['name'];
      $item['has_base'] = TRUE;
      $records[$item['name']] = $item;
    }

    $names = array_unique($names);

    foreach ($names as $name) {
      $info = [
        'name' => $name,
        'module_name' => _afform_angular_module_name($name, 'camel'),
        'directive_name' => _afform_angular_module_name($name, 'dash'),
      ];
      // Skip if it does not match requested name
      foreach ($getNames as $key => $namesList) {
        if (!in_array($info[$key], $namesList)) {
          unset($records[$name]);
          continue 2;
        }
      }
      $record = $scanner->getMeta($name, $getLayout);
      // Skip if it does not exist or is not of requested type(s)
      if (
        (!$record && !isset($records[$name])) ||
        ($getTypes && isset($record['type']) && !in_array($record['type'], $getTypes, TRUE))
      ) {
        unset($records[$name]);
        continue;
      }
      $records[$name] = array_merge($records[$name] ?? [], $record ?? [], $info);
      if (isset($records[$name]['permission']) && is_string($records[$name]['permission'])) {
        $records[$name]['permission'] = explode(',', $records[$name]['permission']);
      }
      // No permissions specified, set default.
      if (empty($records[$name]['permission'])) {
        $records[$name]['permission'] = ['access CiviCRM'];
      }
      if (!$this->checkPermission($records[$name])) {
        unset($records[$name]);
        continue;
      }
      if ($getComputed) {
        $scanner->addComputedFields($records[$name]);
      }
      if ($getSearchDisplays && !empty($records[$name]['layout'])) {
        $records[$name]['search_displays'] = $this->getSearchDisplays($records[$name]['layout']);
      }
      if (!isset($records[$name]['placement']) && $this->_isFieldSelected('placement')) {
        self::convertLegacyPlacement($records[$name]);
      }
      if (!isset($records[$name]['placement_filters'])) {
        self::convertLegacyPlacementOptions($records[$name]);
      }
    }

    // Format layouts
    if ($getLayout) {
      foreach ($records as $name => $record) {
        if (isset($record['layout'])) {
          $this->convertLegacyContactTypes($records[$name]['layout']);
          if ($this->layoutFormat !== 'html') {
            $records[$name]['layout'] = $this->convertHtmlToOutput($records[$name]['layout']);
          }
        }
      }
    }

    // Fetch submission aggregates in bulk
    $this->addExtraComputedFields($records);

    return $records;
  }

  /**
   * Assert that an item is authorized.
   *
   * @return bool
   */
  protected function checkPermission($record) {
    if (!$this->checkPermissions) {
      return TRUE;
    }
    if (($record['permission_operator'] ?? NULL) === 'OR') {
      $record['permission'] = [$record['permission']];
    }
    return \CRM_Core_Permission::check($record['permission']);
  }

  /**
   * Find search display tags in markup
   *
   * @param string $html
   * @return string[]
   */
  private function getSearchDisplays(string $html) {
    $tags = $searchDisplays = [];
    preg_match_all('/<\\s*crm-search-display[^>]+>/', $html, $tags);
    foreach ($tags[0] ?? [] as $tag) {
      $searchName = $displayName = [];
      preg_match('/search-name\\s*=\\s*[\'"]([^\'"]+)[\'"]/', $tag, $searchName);
      preg_match('/display-name\\s*=\\s*[\'"]([^\'"]+)[\'"]/', $tag, $displayName);
      if (!empty($searchName[1])) {
        $searchDisplays[] = $searchName[1] . (empty($displayName[1]) ? '' : '.' . $displayName[1]);
      }
    }
    return $searchDisplays;
  }

  /**
   * Backward-compatibility conversion of <af-entity> Contact tags
   * to use contact-type-specific API entity names.
   *
   * @param string $layout
   * @return void
   */
  private static function convertLegacyContactTypes(&$layout): void {
    if (!$layout || !is_string($layout)) {
      return;
    }
    $regex1 = <<<'REGEX'
      /<af-entity([^>]+)type\s*=\s*["']Contact["']([^>]*)data\s*=\s*"\{([^>]*)'?contact_type'?\s*:\s*'(Individual|Household|Organization)'\s*,?/
      REGEX;
    $layout = preg_replace($regex1, '<af-entity$1type="$4"$2data="{', $layout);
    $regex2 = <<<'REGEX'
      /<af-entity([^>]+)data\s*=\s*"\{([^>]*)'?contact_type'?\s*:\s*'(Individual|Household|Organization)'\s*,?([^>]+)type\s*=\s*["']Contact["']/
      REGEX;
    $layout = preg_replace($regex2, '<af-entity$1data="{$2$4type="$3"', $layout);
  }

  private static function convertLegacyPlacement(array &$record): void {
    $record['placement'] = [];
    if (!empty($record['is_dashlet'])) {
      $record['placement'][] = 'dashboard_dashlet';
    }
    if (!empty($record['is_token'])) {
      $record['placement'][] = 'msg_token';
    }
    if (!empty($record['contact_summary'])) {
      $record['placement'][] = 'contact_summary_' . $record['contact_summary'];
    }
    unset($record['is_dashlet'], $record['is_token'], $record['contact_summary']);
  }

  private static function convertLegacyPlacementOptions(array &$record): void {
    $record['placement_weight'] ??= $record['summary_weight'] ?? NULL;
    $record['placement_filters'] = [];
    if (!empty($record['summary_contact_type'])) {
      $record['placement_filters']['contact_type'] = $record['summary_contact_type'];
    }
    unset($record['summary_weight'], $record['summary_contact_type']);
  }

}
